<div class="page-content clearfix sidebar-page">
                <!-- .page-content-wrapper -->
    <div class="page-content-wrapper">
        <div class="page-content-inner">
            <!-- Start .page-content-inner -->
            <div id="page-header" class="clearfix">
                <div class="page-header">
                    <h2>Usuário</h2>
                    <span class="txt"></span>
                    <div id="teste"></div>
                </div>
                 
            </div>
            <!-- Start .row -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title" id="lanacamento" >Adicionar</h4>
                </div>
                <div class="panel-body pt0 pb0">
                    <form class="form-horizontal group-border stripped" action="add">
                        <div class="container-fluid pagina3">
                            <div class="row">
                                <div class="col-md-7 col-md-offset-2">
                                    <div class="text-center">
                                        <label class="col-md-3 label_personalizado">Nome Completo:</label>
                                        <div class="col-md-8">
                                            <input type="text" maxlength="60"  required name="nome"  class="form-control_alisson required">
                                        </div>
                                        
                                        <label class="col-md-3 label_personalizado">Nome De Usuário:</label>
                                        <div class="col-md-8">
                                            <input type="text" maxlength="60"  required name="usuario"  class="form-control_alisson required">
                                        </div>
                                        
                                        <label class="col-md-3 label_personalizado">Senha:</label>
                                        <div class="col-md-8 space bottom">
                                            <input  type="password" name="senha" required maxlength="20" class="form-control_alisson">
                                        </div>
                                        
                                        <div class="col-md-6 col-md-offset-4">
                                            <button type="submit" class="btn btn-success mr5 mb10" >Salvar</button>
                                            <a href="<?= caminho_raiz();?>usuario/usuario" class="btn btn-success mr5 mb10"><i class="fa fa-reply"></i> &nbsp;Voltar</a>
                                        </div>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </form>    
                </div>
            </div>    
            <!-- End .row -->
        </div>
        <!-- End .page-content-inner -->
    </div>
                <!-- / page-content-wrapper -->
</div>




