<div class="page-content clearfix sidebar-page">
    <div class="page-content-wrapper">
        <div class="page-content-inner">
            <!-- Start .page-content-inner -->
            <div id="page-header" class="clearfix">
                <div class="page-header">
                    <h2></h2>
                    
                </div>
            </div>
            <!-- Start .row -->
            
                <div class="row invoice row-printable">
                    
                        <div class="col-lg-12 col-md-12">
                   
                            <div class="panel panel-default plain toggle panelClose panelRefresh">

                                <div class="panel-body">
                                    <div class="col-md-4">
                                        <h1><?= dias_semana();?></h1>
                                        <a href="javascript:;" onclick="home.pagamento()" class="btn btn-success mr5 mb10 pull-left"><i class="fa fa-plus-circle"></i> &nbsp;Gerar Faturas</a>
                                        <a href="javascript:;" onclick="home.juros()" class="btn btn-success mr5 mb10 pull-left"><i class="fa fa-plus-circle"></i> &nbsp;Gerar Juros</a>
                                    </div>

                                    
                                    
                                </div>

                            </div>

                        </div>
                    
                <!-- col-lg-12 end here -->
                </div>
            
           
        </div>
        <!-- End .page-content-inner -->
    </div>