</div>        
<div id="back-to-top"><a href="#">Back to Top</a>

</div>
    
    <?php Cjs_raiz_P_D(); ?>
    

    <script>
    window.jQuery || document.write('<script src="<?=caminho_raiz()?>assets/js/libs/jquery-2.1.1.min.js">\x3C/script>')
    </script>

    <script>
    window.jQuery || document.write('<script src="<?=caminho_raiz()?>assets/js/libs/jquery-ui-1.10.4.min.js">\x3C/script>')
    </script>

        
    </body>
</html>