<div id="btncollapzion" class=" btn_collapzion"></div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content ">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Area Do Administrador</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body pt-3 pb-3">

                <form id="materialForm" class="form usuario_adm">

                    <div class="row">

                        <div class="col-md-6 my-2">
                            <label class="labels" style="color: black;" for="usuer">Usuario</label>
                            <input style="color: black;" required="required" type="text" class="formInput" id="usuer" name="usuario">
                        </div>
                        <div class="col-md-6 my-2">
                            <label class="labels" style="color: black;" for="senha_adm">Senha</label>
                            <input style="color: black;" required="required" type="password" class="formInput" id="senha_adm" name="senha">
                        </div>
                        
                    </div>

                </form>

                <div class="modal-footer">
                    <div class="col-md-12 my-2" style="text-align: center;">
                        <a href="javascript:;" onclick="home.log_adm()" class="button btn-primary-outline" style="float: none;">Logar</a>
                    </div>
                </div>

                
            </div>
              
          </div>
        </div>
      </div>
    
    
    
    <script src="<?= caminho_raiz()?>mobrise/assets/web/assets/jquery/jquery.min.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/tether/tether.min.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/jquery-mb-ytplayer/jquery.mb.ytplayer.min.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/jquery-mb-vimeo_player/jquery.mb.vimeo_player_min.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/as-pie-progress/jquery-as-pie-progress.min.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/smooth-scroll/smooth-scroll.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/jarallax/jarallax.min.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/viewport-checker/jquery.viewportchecker.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/masonry/masonry.pkgd.min.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/imagesloaded/imagesloaded.pkgd.min.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/bootstrap-carousel-swipe/bootstrap-carousel-swipe.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/theme/js/script.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/mobirise-gallery/player.min.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/mobirise-gallery/script.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/mobirise-slider-video/script.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/formoid/formoid.min.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/js/materialForm.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/js/index.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/js/responsiveslides.min.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/js/slide.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/animed/wow.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/animed/jquery.toaster.js"></script>
    <script src="<?= caminho_raiz()?>mobrise/assets/animed/menu/menu-js.js"></script>
    <script src="<?= caminho_raiz()?>assets/plugins/forms/maskedinput/jquery.mask.min.js"></script>
    <script>
        new WOW().init();
    </script>
    <script src="<?=caminho_raiz()?>assets/js/index.js"></script>
    <script src="<?=caminho_raiz()?>App/modules/home/View/home/js/scripts-home.js"></script>
    
  
  
</body>
</html>