<div id="header" class="page-navbar">
    <!-- .navbar-brand -->
    <a href="<?= caminho_raiz();?>" class="navbar-brand hidden-xs hidden-sm">
        <img src="<?php echo caminho_raiz();?>assets/img/logo.png" class="logo hidden-xs" alt="Dynamic logo">
        <img src="<?php echo caminho_raiz();?>assets/img/logosm.png" class="logo-sm hidden-lg hidden-md" alt="Dynamic logo">
    </a>
    <!-- / navbar-brand -->
    <!-- .no-collapse -->
    <div id="navbar-no-collapse" class="navbar-no-collapse">
        <!-- top left nav -->
        <ul class="nav navbar-nav">
            <li class="toggle-sidebar">
                <a href="#">
                    <i class="fa fa-reorder"></i>
                    <span class="sr-only">Collapse sidebar</span>
                </a>
            </li>
            <li>
                <a href="<?= caminho_raiz();?>"  title="Home"><i class="glyphicon glyphicon-home"></i></a>
            </li>
        </ul>
        <!-- / top left nav -->
        <!-- top right nav -->
        <ul class="nav navbar-nav navbar-right">
            
            <li>
                <a href="javascript:;" onclick="Logout()">
                    <i class="fa fa-power-off"></i>
                    <span class="sr-only">Logout</span>
                </a>
            </li>
            
        </ul>
        <!-- / top right nav -->
    </div>
    <!-- / collapse -->
</div>

<div id="wrapper">
    <!-- .page-sidebar -->
    <aside id="sidebar" class="page-sidebar hidden-md hidden-sm hidden-xs">
        <!-- Start .sidebar-inner -->
        <div class="sidebar-inner">
            <!-- Start .sidebar-scrollarea -->
            <div class="sidebar-scrollarea">
                <!--  .sidebar-panel -->
                <div class="sidebar-panel">
                    <h5 class="sidebar-panel-title">Perfil</h5>
                </div>
                <!-- / .sidebar-panel -->
                <div class="user-info clearfix">
                    <?php $src = caminho_raiz().'/Upload/Usuario/'.retorna_cookie('id').'/'.retorna_cookie('img')?>
                    <img id="user" src="<?=(empty(retorna_cookie('img'))?caminho_raiz()."assets/img/avatars/128.jpg":$src)?>" alt="avatar">
                    
                    <span class="name" id="nome_usuario"></span>
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs"><i class="l-basic-gear"></i>
                        </button>
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">Config <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu right " role="menu">
     
                        <li class="divider"></li>
                                <li><a href="<?= caminho_raiz()?>usuario/usuario/perfil"><i class="glyphicon glyphicon-user"></i>Alterar Foto</a>
                                </li>
                                <li><a href="javascript:;" onclick="Logout()"><i class="fa fa-power-off"></i>Logout</a>
                                </li>
                            
                            
                            
                        </ul>
                    </div>
                </div>
                <!--  .sidebar-panel -->
                <div class="sidebar-panel">
                    <h5 class="sidebar-panel-title">Navegação</h5>
                </div>
                <!-- / .sidebar-panel -->
                <!-- .side-nav -->
                <div class="side-nav">
                    <ul class="nav">
                        <li>
                            <a href="#"><i class="fa fa-folder-open-o"></i><span class="txt">Cadastro</span></a>
                            <ul class="sub">
                                <li><a href="<?= caminho_raiz();?>cadastro/jogador"><span class="txt">Jogador</span></a>
                                </li>
                            </ul>
                            <a href="#"><i class="fa fa-futbol-o"></i><span class="txt">Sorteio</span></a>
                            <ul class="sub">
                                <li><a href="<?= caminho_raiz();?>sorteio/sorteio"><span class="txt">Sorteio</span></a>
                                </li>
                            </ul>
                        </li>
                        
                    </ul>
                </div>
                <!-- / side-nav -->
                <!--  .sidebar-panel -->
                
                
                
                <div class="sidebar-panel">
                    <h5 class="sidebar-panel-title">&nbsp;&nbsp;</h5>
                </div>
                
            </div>
            <!-- End .sidebar-scrollarea -->
        </div>
        <!-- End .sidebar-inner -->
    </aside>   
